#ifndef matrix_h
#define matrix_h

/* Generated by mgclex, the simplest lexer-generator in the northeast */

enum TKSymbol {
LPAREN,
RPAREN,LSQB,RSQB,DASH,KLEENE_STAR,
OR,NEGATE,PERIOD,QMARK,KLEENE_PLUS,
LETTER, TK_EOI
};
static const char* tokenStr[] = {
"LPAREN",
"RPAREN","LSQB","RSQB","DASH","KLEENE_STAR",
"OR","NEGATE","PERIOD","QMARK","KLEENE_PLUS",
"LETTER", "TK_EOI"
};
static const int mgc_lexer_matrix_row1[] = { 73,  40,2,  41,3,  42,8,  43,12,  45,7,  46,10,  48,13,  49,13,  50,13,  51,13,  52,13,  53,13,  54,13,  55,13,  56,13,  57,13,  63,11,  65,13,  66,13,  67,13,  68,13,  69,13,  70,13,  71,13,  72,13,  73,13,  74,13,  75,13,  76,13,  77,13,  78,13,  79,13,  80,13,  81,13,  82,13,  83,13,  84,13,  85,13,  86,13,  87,13,  88,13,  89,13,  90,13,  91,5,  93,6,  94,9,  97,13,  98,13,  99,13,  100,13,  101,13,  102,13,  103,13,  104,13,  105,13,  106,13,  107,13,  108,13,  109,13,  110,13,  111,13,  112,13,  113,13,  114,13,  115,13,  116,13,  117,13,  118,13,  119,13,  120,13,  121,13,  122,13,  124,4, 0};
static const int *mgc_lexer_matrix[] = {
NULL,
mgc_lexer_matrix_row1,
NULL,
NULL,
NULL,
NULL,
NULL,
NULL,
NULL,
NULL,
NULL,
NULL,
NULL,
NULL
};

static const int mgc_lex_accept[14] = {
	-1,
	-1,
	0,
	1,
	6,
	2,
	3,
	4,
	5,
	7,
	8,
	9,
	10,
	11
};

#endif