#ifndef matrix_h
#define matrix_h

/* Generated by mgclex, the simplest lexer-generator in the northeast */

enum TKSymbol {
LPAREN,
RPAREN,LSQB,RSQB,DASH,KLEENE_STAR,
OR,ESCAPE,NEGATE,PERIOD,QMARK,
KLEENE_PLUS,CHAR, TK_EOI
};
static const char* tokenStr[] = {
"LPAREN",
"RPAREN","LSQB","RSQB","DASH","KLEENE_STAR",
"OR","ESCAPE","NEGATE","PERIOD","QMARK",
"KLEENE_PLUS","CHAR", "TK_EOI"
};
static const int mgc_lexer_matrix_row1[] = { 94,  32,14,  33,14,  34,14,  36,14,  37,14,  38,14,  39,14,  40,2,  41,3,  42,8,  43,13,  44,14,  45,7,  46,11,  47,14,  48,14,  49,14,  50,14,  51,14,  52,14,  53,14,  54,14,  55,14,  56,14,  57,14,  58,14,  59,14,  60,14,  61,14,  62,14,  63,12,  64,14,  65,14,  66,14,  67,14,  68,14,  69,14,  70,14,  71,14,  72,14,  73,14,  74,14,  75,14,  76,14,  77,14,  78,14,  79,14,  80,14,  81,14,  82,14,  83,14,  84,14,  85,14,  86,14,  87,14,  88,14,  89,14,  90,14,  91,5,  92,9,  93,6,  94,10,  95,14,  96,14,  97,14,  98,14,  99,14,  100,14,  101,14,  102,14,  103,14,  104,14,  105,14,  106,14,  107,14,  108,14,  109,14,  110,14,  111,14,  112,14,  113,14,  114,14,  115,14,  116,14,  117,14,  118,14,  119,14,  120,14,  121,14,  122,14,  123,14,  124,4,  125,14,  126,14, 0};
static const int *mgc_lexer_matrix[] = {
NULL,
mgc_lexer_matrix_row1,
NULL,
NULL,
NULL,
NULL,
NULL,
NULL,
NULL,
NULL,
NULL,
NULL,
NULL,
NULL,
NULL
};

static const int mgc_lex_accept[15] = {
	-1,
	-1,
	0,
	1,
	6,
	2,
	3,
	4,
	5,
	7,
	8,
	9,
	10,
	11,
	12
};

#endif